### ISSUE TITLE
Could not flock file

### ISSUE THREAD

**Issue by ghost** [ldelgado-serrano/mycofier#2]
I ahve commented out "use threads" as advised. Now get this error:

MycofierClassificatorPERL.pl -infile filt_.fasta -outfile tax_myco.txt -numthreads 20
readline() on closed filehandle SEQ at /home/theoa/bin/mycofier/PERL/MycofierClassificatorPERL.pl line 140.
Could not flock file

Example lines of my fasta file:

> I1-L1-ITS_1
> AAGTCGTAACAAGGTCTCCGTTGGTGAACCAGCGGAGGGATCATTACCGAGTTTACACTCATAACCCTTTGTGAACATTA
> TAACTTGTTGCTTCGGCGGCTTCTGCCCTTCGGGGTGCTGCCCGCCGGCAGTTTCAGTATCTCTGTTTGTACCCGACGAT
> ACATCTGAGTGTTCTTAGCGAACTATAAAAACTTTTAACAACGGATCTCTTGGTTCTA
> I1-L1-ITS_3
> AAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTACTGCTTGCTTATGGCGTTGTCTCGGGAAACCGGG
> GCAGCGTCAGGCATGCTACCCTTGTCTATTCATACCATTTGTTACTTCCCTCGGCGGGGCAACCCGCCGCTGGGGACAAC
> TAAACCCTTCTGTATTAAGCATCAAATCTGAAACAAACAAAATAATCACAACTTTTAACAATGGATCTCTTGGTTCTGGC
> ATCGATGAACA

**Comment by ldelgado-serrano** [comment]
we updated the code. Please download the files again, and follow the readme instructions. 
Let us know if it works!

**Comment by ghost** [comment]
Hi,

sorry, still does not work. Get this error with my own data and with example data:

MycofierClassificatorPERL.pl -infile  /home/theoa/bin/mycofier/PERL/ExampleITSFasta.fasta -outfile tax_myco.txt -numthreads 20
readline() on closed filehandle SEQ at /home/theoa/bin/mycofier/PERL/MycofierClassificatorPERL.pl line 140.
Could not flock file

Theo

Dr Theo Allnutt
Bioinformatics Research Fellow
School of Medicine, Faculty of Health
Waurn Ponds Campus
0352479571

[cid:image001.png@01D24980.EFBE3FB0]

Deakin University
Locked Bag 20000, Geelong, VIC 3220
+61 3 524 79571
theo.allnutt@deakin.edu.au<mailto:theo.allnutt@deakin.edu.au>
www.deakin.edu.au<http://www.deakin.edu.au/>
Deakin University CRICOS Provider Code 00113B

Important Notice: The contents of this email are intended solely for the named addressee and are confidential; any unauthorised use, reproduction or storage of the contents is expressly prohibited. If you have received this email in error, please delete it and any attachments immediately and advise the sender by return email or telephone.

Deakin University does not warrant that this email and any attachments are error or virus free.

**Comment by ldelgado-serrano** [comment]
For the moment all files must be within the same directory and executed within the directory, including the perl script. 
Please let us now.

Thanks.

**Comment by ldelgado-serrano** [comment]
For the moment, all files must be in the same directory including the perl script, that must be executed within the directory.

Thanks for letting us know.

**Comment by ghost** [comment]
Hi,

yes, tried that but still had same problem. I fixed a syntax error on line 68:
open (OUT, ">$outfile") ;

to:

open (OUT, ">","$outfile") or die "Could not open '$outfile' - $!";

and commented out line 73:
#flock(OUT, LOCK_EX) || die "Could not flock file\n";

the program then worked, but I suspect it was making errors overwriting the same file with different threads.. but I'm not sure, I do not know Perl.

Perhaps you could write each thread output to a different temp file or to memory then concatenate it. But as I say, I'm completely guessing what flock does.

I have also realised now that mycofier does not count taxa to produce an otu table, so it would need a bit more scripting to do that and it does not give the full taxonomy, so can't be used to get an LCA with better score, so unfortunately I cannot use it.

Thanks for the work, I'm sure many others will find it very useful.. it probably just won't work on my Perl version for some reason.. no-one else seems to have had a problem

Theo





Dr Theo Allnutt
Bioinformatics Research Fellow
School of Medicine, Faculty of Health
Waurn Ponds Campus
0352479571

[cid:image001.png@01D24A20.A978F090]

Deakin University
Locked Bag 20000, Geelong, VIC 3220
+61 3 524 79571
theo.allnutt@deakin.edu.au<mailto:theo.allnutt@deakin.edu.au>
www.deakin.edu.au<http://www.deakin.edu.au/>
Deakin University CRICOS Provider Code 00113B

Important Notice: The contents of this email are intended solely for the named addressee and are confidential; any unauthorised use, reproduction or storage of the contents is expressly prohibited. If you have received this email in error, please delete it and any attachments immediately and advise the sender by return email or telephone.

Deakin University does not warrant that this email and any attachments are error or virus free.

**Comment by ghost** [comment]
Hi,

yes, tried that but still had same problem. I fixed a syntax error on line 68:
open (OUT, ">$outfile") ;

to:

open (OUT, ">","$outfile") or die "Could not open '$outfile' - $!";

and commented out line 73:
#flock(OUT, LOCK_EX) || die "Could not flock file\n";

the program then worked, but I suspect it was making errors overwriting the same file with different threads.. but I'm not sure, I do not know Perl.

Perhaps you could write each thread output to a different temp file or to memory then concatenate it. But as I say, I'm completely guessing what flock does.

I have also realised now that mycofier does not count taxa to produce an otu table, so it would need a bit more scripting to do that and it does not give the full taxonomy, so can't be used to get an LCA with better score, so unfortunately I cannot use it. 

Thanks for the work, I'm sure many others will find it very useful.. it probably just won't work on my Perl version for some reason.. no-one else seems to have had a problem

Theo

**Comment by ldelgado-serrano** [comment]
Hi, 

Sorry to hear still doesn't work in your environment, we tested it several mac systems and linux systems without any problem. Perhaps you could give us an idea of your setup for us to try to reproduce the error.
